routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoriesPostsController;


//LOCALHOST DIRECT TO HOME PAGE
Route::get('/', [PostController::class, 'index'])->name('index');  //Go to the userController index methode


//RESOURCE ROUTES
Route::resource('user', UserController::class); //Makes route names like user + actions = user.index for all the resources
Route::resource('post', PostController::class);
Route::resource('comment', CommentController::class)->except('create', 'destroy');
Route::get('comment/{post}/create', [CommentController::class, 'create'])->name('comment.create');
Route::get('comment/{comment}/destroy', [CommentController::class, 'destroy'])->name('comment.destroy');
Route::resource('category', CategoryController::class);
Route::resource('category.post', CategoriesPostsController::class);


//OTHER ROUTES
Route::get('/about', function () {  //To redirect to a view with a route name
    return view('/about');
});
Route::get('/login', function () {
    return view('/login');
});
Route::get('/premium', function () {
    return view('/premium');
});
Route::put('update/premium-status', [UserController::class, 'updatePremium'])->name('user.premium');;

//AUTHENTICATION ROUTES
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $guarded = ['user_id', 'created_at', 'updated_at'];


    public function user()
    {   //Posts table belongs to one cell in the users table through the User model
        return $this->belongsTo(User::class);
    }

    public function categories()
    {   //Posts table belongs to many cells in the categories table through the Category model
        return $this->belongsToMany(Category::class);
    }

    public function comments()
    {   //Posts table has many relations with the comments table through the Comment model
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;


use App\Models\Post;
use App\Http\Requests\PostRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with('user', 'categories')->OrderByDesc('created_at')->where('visible', 0)->get();

        if (Auth::user() && Auth::user()->abbo_active) {   //it will check for booleans values is true if not what else
            //Eager loading. Get all the posts and the relations in the user and categories table 
            $posts = Post::with('user', 'categories')->OrderByDesc('created_at')->get();
        }
        //Sends a $post object to use in the user.index view file 
        return view('index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()) {
            return view('post.create');
        } else {
            return redirect()->route('login');
        };
    }

    /**
     * Store a newly created resource in storage.
     * @param  \App\Http\Requests\PostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        // dd($request);
        //Create a new post in a row off the Post model/database
        $post = new Post();   //Store single cells in new row
        $post->user_id = Auth::id();   //Get id of the current user
        $post->title = $request->title;
        $post->content = $request->content;

        if ($path = $request->file('image')) {
            $path = $request->file('image')->store('images');
            $post->image =  $path;
        }

        $post->visible = $request->visible;  //Boolean
        $post->save();  //Save the request by de hand of de model

        $post->categories()->attach($request->category_id);  //


        // if ($request->hasFile('image')) {

        // }

        // $category = new category();  //Store one to one or one to many
        // $category->email = $email;
        // $post->category()->save($categories);

        // $categoryPost = new CategoryPost();  //Store many to many
        // $categoryPost->categoryPost()->attach([  //attach or sync To insert the data into pivot table you can use the attach method on the relationship
        //    $post->id,
        //    $categories->id
        // ]);

        return redirect()->route('index');
    }

    /**
     * Display the specified resource.
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)  //Route model Binding. Gets all the post model/table as a object in the $post value
    {
        //Route model Binding. To find a specific post that also loads the table relations
        $post->load('user', 'categories', 'comments');
        return view('post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $post->load('user', 'categories');
        return view('post.edit', compact('post'));  // , ['categories' => Category::all()]
    }

    /**
     * Update the specified resource in storage.
     * @param  \App\Http\Requests\PostRequest  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, Post $post)
    {
        $post->fill($request->validated());  //A object from the request validation to fill the value of $post
        $post->save();
        return redirect()->route('post.show', $post->id);

        //     $post->user_id =  $request->get('user_id');  //Getting values from the request of the database grocery
        //     $post->title = $request->get('title');
        //     $post->content = $request->get('content');
        //     $post->visible = $request->get('visible');
        //     $post->save();
        //     return redirect()->route('post.show', $post->id);
        //     //return redirect()->back(); //->with('status','Student Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();  //add ->onDelete('cascade') to all the foreignId
        return redirect()->route('index');
    }
}

resources/views/post/create.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

@if ($errors->any())
<div class="alert alert-danger">
   <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
   </ul>
</div>
@endif

<div class="formBlock">
   <h1>Create a new post</h1>

   <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
      @csrf
      <input type="text" name="title" placeholder="Title...">
      <br>
      <select type="text" name="category_id[]" multiple>
         <!-- multiple -->
         @foreach ($categories as $category)
         <option value="{{$category->id}}">{{$category->title}}</option>
         @endforeach
      </select>
      <a href="{{route('category.create')}}">Add category</a>
      <br><br>
      <textarea name="content" rows="5" cols="70">Your story of the day...</textarea>
      <br>
      <div class="">
         Add a image:
         <input class="" type="file" name="image">
      </div>
      <br>
      <input type="hidden" id="1" name="visible" value="0">
      <input type="checkbox" id="1" name="visible" value="1">
      <label for="1">Private</label>
      <br><br>

      <button class="button" type="submit">Post it</button>
   </form>
</div>

@endsection

resources/views/post/edit.blade.php
<?php

use Symfony\Component\Console\Input\Input;
?>
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

<div class="formBlock">
   <h1>Edit your post</h1>

   @if ($errors->any())
   <div class="alert alert-danger">
      <ul>
         @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
         @endforeach
      </ul>
   </div>
   @endif

   <form method="PUT" action="{{route('post.update', $post->id)}}">
      @csrf
      <input type="text" name="title" value=<?= $post->title ?>>
      <br>
      <select type="text" name="category_id">
         <!-- multiple -->
         @foreach ($post->categories as $category)
         <option value="{{$category->id}}">{{$category->title}}</option>
         @endforeach
      </select>
      <br><br>
      <textarea name="content" rows="7" cols="70" value=<?= $post->content ?>><?= $post->content ?></textarea>
      <br>
      <div class="">
         Add a image:
         <input class="" type="file" name="image">
      </div>
      <br>
      <input type="hidden" id="1" name="visible" value="0">
      <input type="checkbox" id="1" name="visible" value="1">
      <label for="1">Private</label>
      <br><br>
      <button class="button" type="submit">Save</button>
      <a class="button" href=" {{ url()->previous() }}">Go Back</a>
   </form>
</div>


<?php
// <select type="text" name="category_id">
// @foreach ($categories as $category)
// <option value="{{$category->id}}">{{$category-> category}}</option>
// @endforeach
// </select>
?>



@endsection

resources/views/post/show.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

<div class="post-container">
   <div class="post-block item1">
      &#128100; {{ $post->user->user_name}}
      <!-- &#129485; -->
   </div>
   <div class="post-block item2">
      @foreach ($post->categories as $category)
      <!--  $category as one loop of the total 
         categories table linked too the $posts object/table -->
      <a class="button category-btn" href="/">{{$category->title}}</a>
      @endforeach
   </div>
   <div class="post-block item3">
      <h3> {{$post->title}}</h3>
      <p> {{$post->content}}</p>
      <br>
      <div class="btn-set">
         <form method="POST" action="{{route('post.destroy', $post->id)}}">
            @method('DELETE')
            <!-- to set the methode to delete -->
            @csrf
            <a class="button" href="{{route('comment.create', $post->id)}}">Comment</a>
            @if($post->user_id == Auth::id())
            <a class="button" href="{{route('post.edit', $post->id)}}">Edit</a>
            <input class="button" type="submit" value="destroy" name="destroy">
            @endif
         </form>
      </div>
   </div>
   <div class="post-block item4">
      <div class="pic-temp">
         <div class="pic-temp">
            @if($post->image)
            <img class="pic-temp" src="{{asset($post->image)}}" alt="your image">
            @endif
            @if ($post->image == Null)
            <img class="pic-temp" src="{{url('images/not-found-image.jpg')}}" alt=" not found image">
            @endif
         </div>
      </div>
      <div class="add-at">
         created at: {{$post->user->created_at}}
      </div>
   </div>

</div>


<?php //dd($post);
?>

@foreach ($post->comments as $comment)

<div class="commentBlock">
   <h4>&#128100; {{$comment->user->user_name}} </h4>
   <p>{{$comment->content}}</p>
   <br>
   @if($comment->user_id == Auth::id())
   <a class="button" href="{{route('comment.edit', $comment->id)}}">Edit</a>
   <a class="button" href="{{route('comment.destroy', $comment->id)}}">Remove</a>
   @endif
   <div class="float-right">
      created at: {{$comment->created_at}}
   </div>
</div>

@endforeach






@endsection