routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoriesPostsController;


//LOCALHOST DIRECT TO HOME PAGE
Route::get('/', [PostController::class, 'index'])->name('index');  //Go to the userController index methode


//RESOURCE ROUTES
Route::resource('user', UserController::class); //Makes route names like user + actions = user.index for all the resources
Route::resource('post', PostController::class);
Route::resource('comment', CommentController::class)->except('create', 'destroy');
Route::get('comment/{post}/create', [CommentController::class, 'create'])->name('comment.create');
Route::get('comment/{comment}/destroy', [CommentController::class, 'destroy'])->name('comment.destroy');
Route::resource('category', CategoryController::class);
Route::resource('category.post', CategoriesPostsController::class);


//OTHER ROUTES
Route::get('/about', function () {  //To redirect to a view with a route name
    return view('/about');
});
Route::get('/login', function () {
    return view('/login');
});
Route::get('/premium', function () {
    return view('/premium');
});
Route::put('update/premium-status', [UserController::class, 'updatePremium'])->name('user.premium');;

//AUTHENTICATION ROUTES
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/about.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')


<div class="aboutBlock">

   <h1>About page</h1>
   <p>Some code in a file to create a web page with linked database tables</p>

</div>

@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/index.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

<div class="list">
   @foreach($posts as $post)
   <!-- Receives a $posts object from the UserController  -->
   <!--  $post as one loop of the total $posts -->

   <div class="post-container">
      <div class="post-block item1">
         &#128100; {{ $post->user->user_name}}
         <!-- &#129485; -->
      </div>
      <div class="post-block item2">
         @foreach ($post->categories as $category)
         <!--  $category as one loop of the total 
               categories table linked too the $posts object/table -->
         <a class="button category-btn" href="{{ route('category.post.index', ['category' => $category->id])}}">{{$category->title}}</a>
         @endforeach
      </div>
      <div class="post-block item3">
         <h3> {{$post->title}}</h3>
         <p> {{$post->content}}</p>
         <br>
         <div class="btn-set">
            <a class="button" href="{{route('post.show', $post->id)}}">view post</a>
            <a class="button" href="{{route('comment.create', $post->id)}}">comment</a>
         </div>
      </div>
      <div class="post-block item4">
         <div class="pic-temp">
            @if($post->image)
            <img class="pic-temp" src="{{asset($post->image)}}" alt="your image">
            @endif
            @if ($post->image == Null)
            <img class="pic-temp" src="{{url('images/not-found-image.jpg')}}" alt=" not found image">
            @endif
         </div>
         <div class="add-at">
            created at: {{$post->user->created_at}}
         </div>
      </div>

   </div>

   @endforeach
</div>

@endsection

resources/views/premium.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')


<div class="aboutBlock">

   <h1>Go premium now!</h1>



   <form method="POST" action="{{route('user.premium')}}">
      @csrf
      @method("PUT")

      <!-- Premium Abbo -->
      <div>

         <input type="checkbox" id="1" name="abbo_active" value="1">
         <label for="1">Premium Abbo on</label>
         <br>
         <input type="checkbox" id="1" name="abbo_active" value="0">
         <label for="1">Premium Abbo off</label>
      </div>
      <br>
      <div>
         <button class="button">
            {{ __('Pay or Change') }}
         </button>
         <br>
         Now just 10,- a month
      </div>
   </form>

</div>

@endsection