routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoriesPostsController;


//LOCALHOST DIRECT TO HOME PAGE
Route::get('/', [PostController::class, 'index'])->name('index');  //Go to the userController index methode


//RESOURCE ROUTES
Route::resource('user', UserController::class); //Makes route names like user + actions = user.index for all the resources
Route::resource('post', PostController::class);
Route::resource('comment', CommentController::class)->except('create', 'destroy');
Route::get('comment/{post}/create', [CommentController::class, 'create'])->name('comment.create');
Route::get('comment/{comment}/destroy', [CommentController::class, 'destroy'])->name('comment.destroy');
Route::resource('category', CategoryController::class);
Route::resource('category.post', CategoriesPostsController::class);


//OTHER ROUTES
Route::get('/about', function () {  //To redirect to a view with a route name
    return view('/about');
});
Route::get('/login', function () {
    return view('/login');
});
Route::get('/premium', function () {
    return view('/premium');
});
Route::put('update/premium-status', [UserController::class, 'updatePremium'])->name('user.premium');;

//AUTHENTICATION ROUTES
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    public function post()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Http\Requests\CategoryRequest;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create', ['category' => Category::all()]);
    }

    /**
     * Store a newly created resource in storage.
     * @param  \App\Http\Requests\CategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = new Category();
        $category->title = $request->title;   //foreignId
        $category->save();  //save the request by de hand of de model

        return redirect()->route('index');
    }

    /**
     * Display the specified resource.
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category  $category)  //Route model Binding. Gets all the post model/table as a object in the $post value
    {
    }

    /**
     * Show the form for editing the specified resource.
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return redirect()->route('category.edit', ['category' => $category, 'category' => Category::all()]);
    }

    /**
     * Update the specified resource in storage.
     * @param  \App\Http\Requests\CategoryRequest  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->title = $request->get('title');   //foreignId
        $category->save();

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index');
    }
}

resources/views/category/create.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

<div class="formBlock">
   <h1>Create a new category</h1>

   @if ($errors->any())
   <div class="alert alert-danger">
      <ul>
         @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
         @endforeach
      </ul>
   </div>
   @endif

   <form method="POST" action="{{ route('category.store') }}">
      <input type="text" name="title" placeholder="Title...">
      <br><br>
      {{csrf_field()}}
      <button type="submit">Create your category</button>
   </form>
</div>

@endsection

resources/views/category/edit.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

<div class="formBlock">
   <h1>Edit a category</h1>

   @if ($errors->any())
   <div class="alert alert-danger">
      <ul>
         @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
         @endforeach
      </ul>
   </div>
   @endif

   <form method="PUT" action="{{route('category.update', $category->id)}}">
      <input type="text" name="title" value="<?= $category->title ?>">
      <br><br>
      {{csrf_field()}}
      <button type="submit">Edit your category</button>
   </form>
</div>

@endsection

resources/views/category/show.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')

<h1>show categories page</h1>

<div class="list">
   @foreach($post as $post)
   <!-- Receives a $posts object from the UserController  -->
   <!--  $post as one loop of the total $posts -->

   <div class="post-container">
      <div class="post-block item1">
         &#128100; {{ $post->user->user_name}}
         <!-- &#129485; -->
      </div>
      <div class="post-block item2">
         @foreach ($post->categories as $category)
         <!--  $category as one loop of the total 
         categories table linked too the $posts object/table -->
         <a class="button category-btn" href="/">{{$category->title}}</a>
         @endforeach
      </div>
      <div class="post-block item3">
         <h3> {{$post->title}}</h3>
         <p> {{$post->content}}</p>
         <br>
         <div class="btn-set">
            <a class="button" href="{{route('post.show', $post->id)}}">view post</a>
            <a class="button" href="{{route('comment.create', $post->id)}}">Comment</a>
         </div>
      </div>
      <div class="post-block item4">
         <div class="pic-temp">
            <img class="pic-temp" src="{{url('/images/not-found-image.jpg')}}" alt="image not found">
         </div>
         <div class="add-at">
            created at: {{$post->user->created_at}}
         </div>
      </div>

   </div>

   @endforeach

</div>

@endsection