routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CategoriesPostsController;


//LOCALHOST DIRECT TO HOME PAGE
Route::get('/', [PostController::class, 'index'])->name('index');  //Go to the userController index methode


//RESOURCE ROUTES
Route::resource('user', UserController::class); //Makes route names like user + actions = user.index for all the resources
Route::resource('post', PostController::class);
Route::resource('comment', CommentController::class)->except('create', 'destroy');
Route::get('comment/{post}/create', [CommentController::class, 'create'])->name('comment.create');
Route::get('comment/{comment}/destroy', [CommentController::class, 'destroy'])->name('comment.destroy');
Route::resource('category', CategoryController::class);
Route::resource('category.post', CategoriesPostsController::class);


//OTHER ROUTES
Route::get('/about', function () {  //To redirect to a view with a route name
    return view('/about');
});
Route::get('/login', function () {
    return view('/login');
});
Route::get('/premium', function () {
    return view('/premium');
});
Route::put('update/premium-status', [UserController::class, 'updatePremium'])->name('user.premium');;

//AUTHENTICATION ROUTES
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__ . '/auth.php';




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;

    public function post()
    {
        return $this->belongsTo(Post::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Comment;
use App\Http\Requests\CommentRequest;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $comment = Comment::with("comment")->get();
        // $comment = comment::find(1)->Comment;
        // return view('comment.index');  //, ['comment' => $comment]
    }

    /**
     * Show the form for creating a new resource.
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        if (Auth::user()) {
            return view('comment.create', ['post' => $post]);
        } else {
            return redirect()->route('login');
        };
        return view('comment.create', ['post' => $post]);
    }

    /**
     * Store a newly created resource in storage.
     * @param  \App\Http\Requests\CommentRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request)
    {
        $comment = new Comment();
        $comment->post_id = $request->post_id;   //foreignId $request->post_id
        $comment->user_id = Auth::id();    //foreignId
        $comment->content = $request->content;
        $comment->visible = $request->visible;  //Boolean
        $comment->save();  //save the request by de hand of de model

        return redirect()->route('post.show', ['post' => $request->post_id]);
    }

    /**
     * Display the specified resource.
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function show(Comment $comment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function edit(Comment $comment)
    {
        $comment->load('user');
        return view('comment.edit', compact('comment'));
    }



    /**
     * Update the specified resource in storage.
     * @param  \App\Http\Requests\CommentRequest  $request
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function update(CommentRequest $request, Comment $comment)
    {
        $comment->post_id = $request->get('post_id');   //foreignId
        $comment->user_id =  $request->get('user_id');  //foreignId
        $comment->content = $request->get('content');
        $comment->visible = $request->get('visible');   //Boolean
        $comment->save();

        return redirect()->route('post.show', ['post' => $request->post_id]);
    }

    /**
     * Remove the specified resource from storage.
     * @param  \App\Models\Comment  $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $post_id = $comment->post_id;   //Set $post_id value in a variable to use it after de delete function
        $comment->delete();
        return redirect()->route('post.show', ['post' => $post_id]);
        //Go back to the post you delete from with a route model binding
    }
}

resources/views/comment/create.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')


<div class="createCommentBlock">
   <h1>Comment on the post</h1>

   @if ($errors->any())
   <div class="alert alert-danger">
      <ul>
         @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
         @endforeach
      </ul>
   </div>
   @endif

   <form method="POST" action="{{ route('comment.store') }}">
      <input type="text" name="title" placeholder="Title...">
      <br><br>
      <textarea name="content" rows="5" cols="70" placeholder="Your comment"></textarea>
      <br><br>
      <input type="hidden" id="1" name="visible" value="false">
      <input type="checkbox" id="1" name="visible" value="true">
      <label for="1">Private</label>
      <br><br>
      <input type="hidden" name="post_id" value="{{$post->id}}" />
      {{csrf_field()}}
      <button class="button" type="submit">Post your comment</button>
      <a class="button" href=" {{ url()->previous() }}">Go Back</a>
   </form>
</div>

@endsection

resources/views/comment/edit.blade.php
@extends('/components/master')

@section('title', 'Homepage')

@section('content')


<div class="formBlock">
   <h1>Edit your post</h1>

   @if ($errors->any())
   <div class="alert alert-danger">
      <ul>
         @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
         @endforeach
      </ul>
   </div>
   @endif

   <form method="PUT" action="{{route('comment.update', $comment->id)}}">

      <input type="text" name="title"><?= $comment->title ?></input>
      <br>
      <textarea name="content" rows="5" cols="70"><?= $comment->content ?></textarea>
      <br><br>
      <input type="hidden" id="1" name="visible" value="false">
      <input type="checkbox" id="1" name="visible" value="true">
      <label for="1">Private</label>
      {{csrf_field()}}
      <button class="button" type="submit">Save your comment</button>
      <a class="button" href=" {{ url()->previous() }}">Go Back</a>
   </form>
</div>

@endsection